name: ⚙️ Deduplicate yarn.lock

on:
  push:
    branches:
      - main
    paths:
      - yarn.lock

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  deduplicate:
    if: github.repository == 'remix-run/examples'
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: ⚙️ Deduplicate yarn.lock
        run: npx yarn-deduplicate && rm -rf ./node_modules && yarn

      - name: 💪 Commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          if [ -z "$(git status --porcelain)" ]; then
            echo "💿 no deduplication needed"
            exit 0
          fi
          git commit -m "chore: deduplicate yarn.lock"
          git push
          echo "💿 https://github.com/$GITHUB_REPOSITORY/commit/$(git rev-parse HEAD)"
