name: 👔 Format

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    if: github.repository == 'remix-run/examples'
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v7

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: 📥 Install deps
        run: yarn --frozen-lockfile

      - name: 👔 Format
        run: yarn format

      # - name: 🦕 Install Deno
      #   uses: denoland/setup-deno@v1
      #   with:
      #     deno-version: vx.x.x

      # - name: 👔 Format Deno files
      #   run: yarn format:deno

      - name: 💪 Commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add .
          if [ -z "$(git status --porcelain)" ]; then
            echo "💿 no formatting changed"
            exit 0
          fi
          git commit -m "chore: format"
          git push
          echo "💿 pushed formatting changes https://github.com/$GITHUB_REPOSITORY/commit/$(git rev-parse HEAD)"
